CREATE TYPE USER_TYPE AS ENUM (
	'STUDENT',
	'LECTURER',
	'ADMIN'
);

CREATE TYPE GENDER_TYPE AS ENUM (
	'FEMALE',
	'MALE',
	'OTHER'
);

CREATE TYPE ACADEMIC_ROLE AS ENUM (
	'LECTURER',
	'RESEARCH_ASSISTANT',
	'DEPARTMENT_HEAD',
	'DEAN',
	'RECTOR'
);

CREATE TYPE ACADEMIC_TITLE AS ENUM (
    'PROFESSOR',
    'ASSOCIATE_PROFESSOR',
    'ASSISTANT_PROFESSOR',
    'DOCTOR_LECTURER',
    'LECTURER',
    'RESEARCH_ASSISTANT',
    'TEACHING_ASSISTANT',
    'INSTRUCTOR',
    'SPECIALIST',
    'VISITING_PROFESSOR'
);

CREATE TYPE ASSESSMENT_TYPE AS ENUM (
	'MIDTERM',
	'FINAL',
	'QUIZ',
	'MAKEUP',
	'PROJECT',
	'HOMEWORK',
	'LAB',
	'PRESENTATION',
	'PRACTICE',
	'ATTENDANCE'
);

CREATE TYPE ATTENDANCE_TYPE AS ENUM (
	'QR_CODE',
	'NFC',
	'SIX_DIGIT_CODE',
	'QR_CODE_NFC',
	'QR_CODE_SIX_DIGIT_CODE',
	'NFC_SIX_DIGIT_CODE',
	'ALL'
);

CREATE TABLE LANGUAGES (
	LANGUAGE_ID SMALLSERIAL PRIMARY KEY,
	LANGUAGE_NAME VARCHAR(32) NOT NULL
);

CREATE TABLE FACULTIES(
	FACULTY_ID SMALLSERIAL PRIMARY KEY,
	FACULTY_NAME VARCHAR(50) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE DEPARTMENTS(
	DEPARTMENT_ID SMALLSERIAL PRIMARY KEY,
	DEPARTMENT_NAME VARCHAR(50) NOT NULL,
	DEPARTMENT_CODE CHAR(4) NOT NULL, --CENG, EENL
	LANGUAGE_ID SMALLINT NOT NULL,
	FACULTY_ID SMALLINT,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),

	CONSTRAINT FK_DEPARTMENT_FACULTY
		FOREIGN KEY (FACULTY_ID)
		REFERENCES FACULTIES(FACULTY_ID),

	CONSTRAINT FK_DEPARTMENT_LANGUAGE
		FOREIGN KEY (LANGUAGE_ID)
		REFERENCES LANGUAGES(LANGUAGE_ID)
);

CREATE TABLE COURSES(
	COURSE_ID UUID PRIMARY KEY,
	COURSE_NAME VARCHAR(50) NOT NULL,
	COURSE_CODE CHAR(7) NOT NULL UNIQUE,
	COURSE_ECTS DECIMAL(3,1) CHECK (COURSE_ECTS > 0),
	COURSE_CREDIT DECIMAL(3,1) CHECK (COURSE_CREDIT > 0),
	HOURS_THEORETICAL SMALLINT NOT NULL CHECK (HOURS_THEORETICAL >= 0 AND HOURS_THEORETICAL <= 10),
	HOURS_PRACTICAL SMALLINT NOT NULL CHECK (HOURS_PRACTICAL >= 0 AND HOURS_PRACTICAL <= 10),
	MIN_ATTENDANCE_PERCENT INT CHECK (MIN_ATTENDANCE_PERCENT >= 0 AND MIN_ATTENDANCE_PERCENT <= 100),
	LANGUAGE_ID SMALLINT NOT NULL,
	IS_ONLINE BOOL NOT NULL,
	IS_ELECTIVE BOOL NOT NULL,
	DEPARTMENT_ID SMALLINT NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),

	CONSTRAINT FK_COURSE_DEPARTMENT
		FOREIGN KEY (DEPARTMENT_ID)
		REFERENCES DEPARTMENTS(DEPARTMENT_ID),

	CONSTRAINT FK_COURSE_LANGUAGE
		FOREIGN KEY (LANGUAGE_ID)
		REFERENCES LANGUAGES(LANGUAGE_ID),

	CONSTRAINT CHK_MIN_COURSE_HOURS
		CHECK (HOURS_THEORETICAL + HOURS_PRACTICAL > 0)
);

CREATE TABLE USERS (
	USER_ID UUID PRIMARY KEY,
	USER_FIRST_NAME VARCHAR(32) NOT NULL,
	USER_LAST_NAME VARCHAR(32) NOT NULL,
	USER_EMAIL VARCHAR(48) NOT NULL UNIQUE,
	USER_PASSWORD VARCHAR(255) NOT NULL,
	GENDER GENDER_TYPE NOT NULL,
	USER_TYPE USER_TYPE NOT NULL,
	DEPARTMENT_ID SMALLINT NOT NULL,
	IS_IN_COURSE BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT TIMESTAMP NOT NULL,

	CONSTRAINT DK_USER_DEPARTMENT
		FOREIGN KEY (DEPARTMENT_ID)
		REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);

CREATE TABLE LECTURERS(
	LECTURER_ID UUID PRIMARY KEY,
	LECTURER_TITLE ACADEMIC_TITLE NOT NULL,
	LECTURER_ROLE ACADEMIC_ROLE NOT NULL DEFAULT 'LECTURER',
	PHONE VARCHAR(15),
	EXT_PHONE VARCHAR(4),

	CONSTRAINT FK_LECTURER_USER
		FOREIGN KEY (LECTURER_ID)
		REFERENCES USERS(USER_ID)
);

CREATE TABLE STUDENTS(
	STUDENT_ID UUID PRIMARY KEY,
	STUDENT_NUMBER VARCHAR(10) NOT NULL UNIQUE,
	YEAR_OF_STUDY INT NOT NULL DEFAULT 0,
	GPA DECIMAL(3,2) NOT NULL DEFAULT 0, --TERM
	CGPA DECIMAL(3,2) NOT NULL DEFAULT 0, --ALL TERMS
	IS_ACTIVE BOOL NOT NULL DEFAULT FALSE,
	IS_IN_CAMPUS BOOL NOT NULL DEFAULT FALSE,

	CONSTRAINT FK_STUDENT_USER
		FOREIGN KEY (STUDENT_ID)
		REFERENCES USERS(USER_ID)
);

CREATE TABLE STUDENT_COURSE (
	STUDENT_ID UUID NOT NULL,
	COURSE_ID UUID NOT NULL,
	ENROLLED_AT TIMESTAMP NOT NULL,
	IS_ACTIVE BOOL NOT NULL DEFAULT TRUE,
	PRIMARY KEY(STUDENT_ID, COURSE_ID),

	CONSTRAINT FK_STUDENT_COURSE_STUDENT
		FOREIGN KEY (STUDENT_ID)
		REFERENCES STUDENTS(STUDENT_ID),

	CONSTRAINT FK_STUDENT_COURSE_COURSE
		FOREIGN KEY (COURSE_ID)
		REFERENCES COURSES(COURSE_ID)
);

CREATE TABLE LECTURER_COURSE (
	LECTURER_ID UUID NOT NULL,
	COURSE_ID UUID NOT NULL,
	ENROLLED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
	IS_ACTIVE BOOL NOT NULL DEFAULT TRUE,
	PRIMARY KEY(LECTURER_ID, COURSE_ID),

	CONSTRAINT FK_LECTURER_COURSE_LECTURER
		FOREIGN KEY (LECTURER_ID)
		REFERENCES LECTURERS(LECTURER_ID),

	CONSTRAINT FK_LECTURER_COURSE_COURSE
		FOREIGN KEY (COURSE_ID)
		REFERENCES COURSES(COURSE_ID)
);

CREATE TABLE GRADES (
	STUDENT_ID UUID NOT NULL,
	COURSE_ID UUID NOT NULL,
	ASSESSMENT_TYPE ASSESSMENT_TYPE NOT NULL,
	GRADE INT NOT NULL CHECK (GRADE >= 0 AND GRADE <= 100),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY(STUDENT_ID, COURSE_ID, ASSESSMENT_TYPE),

	CONSTRAINT FK_GRADE_STUDENT
		FOREIGN KEY (STUDENT_ID)
		REFERENCES STUDENTS(STUDENT_ID),
	CONSTRAINT FK_GRADE_COURSE
		FOREIGN KEY (COURSE_ID)
		REFERENCES COURSES(COURSE_ID)
);

CREATE TABLE ATTENDANCES (
	ATTENDANCE_ID UUID PRIMARY KEY,
	COURSE_ID UUID NOT NULL,
	NFC_PATH UUID,

	LATITUDE DECIMAL(9,6),
	LONGITUDE DECIMAL(9,6),
	ALLOWED_RADIUS_METERS INT DEFAULT 50,
	ALLOWED_ATTENDANCE_TYPE ATTENDANCE_TYPE NOT NULL,
	SESSION_HOURS SMALLINT NOT NULL DEFAULT 1 CHECK (SESSION_HOURS > 0 AND SESSION_HOURS <= 10), --how many courses opened at the same time.

	STARTED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
	EXPIRES_AT TIMESTAMP NOT NULL,
	IS_ACTIVE BOOL NOT NULL DEFAULT TRUE,

	CONSTRAINT FK_ATTENDANCE_COURSE
		FOREIGN KEY (COURSE_ID)
		REFERENCES COURSES(COURSE_ID)
);

CREATE TABLE ATTENDANCE_SESSIONS (
	ATTENDANCE_SESSION_ID UUID PRIMARY KEY,
	ATTENDANCE_ID UUID NOT NULL,
	SIX_DIGIT_CODE CHAR(6) CHECK (SIX_DIGIT_CODE ~ '^[0-9]{6}$'),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
	EXPIRES_AT TIMESTAMP NOT NULL,
	IS_ACTIVE BOOL NOT NULL DEFAULT TRUE,

	CONSTRAINT FK_ATT_SESSIONS_ATTENDANCE
		FOREIGN KEY (ATTENDANCE_ID)
		REFERENCES ATTENDANCES(ATTENDANCE_ID)
);

CREATE TABLE ATTENDANCE_RECORDS (
	ATTENDANCE_RECORD_ID SERIAL PRIMARY KEY,
	STUDENT_ID UUID NOT NULL,
	ATTENDANCE_ID UUID NOT NULL,
	ATTENDANCE_SESSION_ID UUID NOT NULL,

	ATTENDANCE_TYPE ATTENDANCE_TYPE NOT NULL,
	CURRENT_LAT DECIMAL(9,6), --latitude
	CURRENT_LONG DECIMAL(9,6), --longitude
	DEVICE_ID UUID NOT NULL,
	CLIENT_IP VARCHAR(45) NOT NULL,
	ATTEND_AT TIMESTAMP NOT NULL DEFAULT NOW(),
	IS_LATE BOOL DEFAULT FALSE,
	UNIQUE(STUDENT_ID, ATTENDANCE_ID),

	CONSTRAINT FK_ATT_RECORD_ATTENDANCE
		FOREIGN KEY (ATTENDANCE_ID)
		REFERENCES ATTENDANCES(ATTENDANCE_ID),

	CONSTRAINT FK_ATT_RECORD_STUDENT
		FOREIGN KEY (STUDENT_ID)
		REFERENCES STUDENTS(STUDENT_ID),

	CONSTRAINT FK_ATT_RECORD_ATT_SESSION
		FOREIGN KEY (ATTENDANCE_SESSION_ID)
		REFERENCES ATTENDANCE_SESSIONS(ATTENDANCE_SESSION_ID)
);