BEGIN;

ALTER TABLE STUDENT_COURSE
    ADD COLUMN TERM_ID SMALLINT REFERENCES TERMS(TERM_ID);

ALTER TABLE LECTURER_COURSE
    ADD COLUMN TERM_ID SMALLINT REFERENCES TERMS(TERM_ID);

ALTER TABLE ATTENDANCES
    ADD COLUMN TERM_ID SMALLINT REFERENCES TERMS(TERM_ID);

ALTER TABLE GRADES
    ADD COLUMN TERM_ID SMALLINT REFERENCES TERMS(TERM_ID);

UPDATE STUDENT_COURSE sc
SET TERM_ID = t.TERM_ID
FROM TERMS t
WHERE sc.TERM_ID IS NULL
  AND t.ACADEMIC_YEAR_START = 2026
  AND t.TERM_TYPE = 'FALL'
  AND sc.ENROLLED_AT::date
      BETWEEN t.TERM_START_DATE AND t.TERM_END_DATE;

UPDATE LECTURER_COURSE lc
SET TERM_ID = t.TERM_ID
FROM TERMS t
WHERE lc.TERM_ID IS NULL
  AND t.ACADEMIC_YEAR_START = 2026
  AND t.TERM_TYPE = 'FALL'
  AND lc.ENROLLED_AT::date
      BETWEEN t.TERM_START_DATE AND t.TERM_END_DATE;

UPDATE ATTENDANCES a
SET TERM_ID = t.TERM_ID
FROM TERMS t
WHERE a.TERM_ID IS NULL
  AND t.ACADEMIC_YEAR_START = 2026
  AND t.TERM_TYPE = 'FALL'
  AND a.STARTED_AT::date
      BETWEEN t.TERM_START_DATE AND t.TERM_END_DATE;

COMMIT;