BEGIN;

CREATE TYPE TERM_TYPE AS ENUM (
	'FALL',
	'SPRING',
	'SUMMER'
);

CREATE TABLE TERMS(
	TERM_ID SMALLSERIAL PRIMARY KEY,
	TERM_NAME VARCHAR(50) NOT NULL UNIQUE,
	ACADEMIC_YEAR_START SMALLINT NOT NULL,
	TERM_START_DATE DATE NOT NULL,
	TERM_END_DATE DATE NOT NULL,
	TERM_TYPE TERM_TYPE NOT NULL,
	
    CONSTRAINT UQ_TERM_YEAR_TYPE
        UNIQUE (ACADEMIC_YEAR_START, TERM_TYPE),

	CONSTRAINT CHK_TERM_DATES
		CHECK (TERM_START_DATE < TERM_END_DATE)
);

COMMIT;