CREATE OR REPLACE VIEW V_REAL_ATTENDANCE_STATS AS
SELECT 
    s.STUDENT_ID,
    c.COURSE_ID,
    c.COURSE_NAME,
    c.COURSE_CODE,
    c.MIN_ATTENDANCE_PERCENT,

    -- Total time for course
    COALESCE(SUM(att.SESSION_HOURS), 0) AS TOTAL_CONDUCTED_HOURS,

    -- Attend time for students
    COALESCE(SUM(CASE WHEN ar.ATTENDANCE_RECORD_ID IS NOT NULL THEN att.SESSION_HOURS ELSE 0 END), 0) AS TOTAL_ATTENDED_HOURS,

    -- Attendance Percentage
    CASE 
        WHEN SUM(att.SESSION_HOURS) = 0 THEN 100.00
        ELSE ROUND(
            (SUM(CASE WHEN ar.ATTENDANCE_RECORD_ID IS NOT NULL THEN att.SESSION_HOURS ELSE 0 END)::DECIMAL 
             / SUM(att.SESSION_HOURS)) * 100, 
            2
        )
    END AS ATTENDANCE_PERCENTAGE,

    -- Latecomers
    COUNT(CASE WHEN ar.IS_LATE = TRUE THEN 1 END) AS TOTAL_LATE_COUNT,

    -- Status (SAFE/CRITICAL)
    CASE 
        WHEN SUM(att.SESSION_HOURS) > 0 AND 
             (SUM(CASE WHEN ar.ATTENDANCE_RECORD_ID IS NOT NULL THEN att.SESSION_HOURS ELSE 0 END)::DECIMAL / SUM(att.SESSION_HOURS)) * 100 < c.MIN_ATTENDANCE_PERCENT 
        THEN 'CRITICAL' 
        ELSE 'SAFE'
    END AS STATUS

FROM STUDENTS s
JOIN STUDENT_COURSE sc ON s.STUDENT_ID = sc.STUDENT_ID AND sc.IS_ACTIVE = TRUE
JOIN COURSES c ON sc.COURSE_ID = c.COURSE_ID
LEFT JOIN ATTENDANCES att ON c.COURSE_ID = att.COURSE_ID AND att.EXPIRES_AT < NOW()
LEFT JOIN ATTENDANCE_SESSIONS ats ON att.ATTENDANCE_ID = ats.ATTENDANCE_ID
LEFT JOIN ATTENDANCE_RECORDS ar ON ats.ATTENDANCE_SESSION_ID = ar.ATTENDANCE_SESSION_ID AND ar.STUDENT_ID = s.STUDENT_ID
GROUP BY s.STUDENT_ID, c.COURSE_ID, c.COURSE_NAME, c.COURSE_CODE, c.MIN_ATTENDANCE_PERCENT;