CREATE OR REPLACE VIEW V_STUDENT_STATUS_DETAILS AS
SELECT 
    -- Student var
    u.USER_FIRST_NAME,
    u.USER_LAST_NAME,
    s.STUDENT_NUMBER,
    
    -- Course var
    c.COURSE_CODE,
    c.COURSE_NAME,
    c.MIN_ATTENDANCE_PERCENT,

    -- Attendance time(total)
    COALESCE(SUM(att.SESSION_HOURS), 0) AS TOTAL_CONDUCTED_HOURS,
    
    -- Attend time(student)
    COALESCE(SUM(CASE WHEN ar.ATTENDANCE_RECORD_ID IS NOT NULL THEN att.SESSION_HOURS ELSE 0 END), 0) AS TOTAL_ATTENDED_HOURS,
    
    -- Attendance percentage
    CASE 
        WHEN SUM(att.SESSION_HOURS) = 0 THEN 100.00
        ELSE ROUND(
            (SUM(CASE WHEN ar.ATTENDANCE_RECORD_ID IS NOT NULL THEN att.SESSION_HOURS ELSE 0 END)::DECIMAL 
             / SUM(att.SESSION_HOURS)) * 100, 
            2
        )
    END AS ATTENDANCE_PERCENTAGE,

    -- Latecomers
    COUNT(CASE WHEN ar.IS_LATE = TRUE THEN 1 END) AS TOTAL_LATE_COUNT,

    -- Status (SAFE/CRITICAL)
    CASE 
        WHEN SUM(att.SESSION_HOURS) > 0 AND 
             (SUM(CASE WHEN ar.ATTENDANCE_RECORD_ID IS NOT NULL THEN att.SESSION_HOURS ELSE 0 END)::DECIMAL / SUM(att.SESSION_HOURS)) * 100 < c.MIN_ATTENDANCE_PERCENT 
        THEN 'CRITICAL'
        ELSE 'SAFE'
    END AS STATUS,

    s.STUDENT_ID,
    c.COURSE_ID

FROM STUDENTS s
JOIN USERS u ON s.STUDENT_ID = u.USER_ID
JOIN STUDENT_COURSE sc ON s.STUDENT_ID = sc.STUDENT_ID AND sc.IS_ACTIVE = TRUE
JOIN COURSES c ON sc.COURSE_ID = c.COURSE_ID
LEFT JOIN ATTENDANCES att ON c.COURSE_ID = att.COURSE_ID AND att.EXPIRES_AT < NOW()
LEFT JOIN ATTENDANCE_RECORDS ar ON att.ATTENDANCE_ID = ar.ATTENDANCE_ID AND ar.STUDENT_ID = s.STUDENT_ID
GROUP BY 
    u.USER_FIRST_NAME, u.USER_LAST_NAME, s.STUDENT_NUMBER,
    s.STUDENT_ID, c.COURSE_ID, c.COURSE_NAME, c.COURSE_CODE, c.MIN_ATTENDANCE_PERCENT;